/**
 * Blueprint export utilities — PDF (jsPDF text-only) and DOCX (docx)
 * Only called client-side.
 */

import type { BlueprintV1 } from '@/types/blueprint'

function dateStr() {
  return new Date().toISOString().slice(0, 10)
}

function safeFilename(name: string) {
  return name.replace(/[^a-zA-Z0-9-_]/g, '-').replace(/-+/g, '-').slice(0, 40)
}

// ── PDF export (text-only, no html2canvas) ────────────────
export async function exportBlueprintPDF(
  blueprint: BlueprintV1,
  versionLabel: string
) {
  const { default: jsPDF } = await import('jspdf')

  const companyName = blueprint.organization?.name || 'Company'
  const date = dateStr()
  const { strategic_objective, system_architecture, workflow_modules, risk_assessment, deployment_plan, diagnostic_summary } = blueprint

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 18
  const contentW = pageW - margin * 2
  let y = margin
  let pageNum = 1

  const addFooter = () => {
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 120)
    doc.text(`Generated by Aivory  |  ${date}  |  ${versionLabel}`, margin, pageH - 6)
    doc.text(`Page ${pageNum}`, pageW - margin, pageH - 6, { align: 'right' })
  }

  const checkPage = (needed = 10) => {
    if (y + needed > pageH - 14) {
      addFooter()
      doc.addPage()
      pageNum++
      y = margin
    }
  }

  const h1 = (text: string) => {
    checkPage(14)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 229, 158)
    doc.text(text, margin, y)
    y += 2
    doc.setDrawColor(0, 229, 158)
    doc.setLineWidth(0.4)
    doc.line(margin, y, margin + contentW, y)
    y += 6
  }

  const h2 = (text: string) => {
    checkPage(10)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(224, 224, 224)
    doc.text(text, margin, y)
    y += 5
  }

  const body = (text: string, indent = 0) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(180, 180, 180)
    const lines = doc.splitTextToSize(text, contentW - indent)
    lines.forEach((line: string) => {
      checkPage(5)
      doc.text(line, margin + indent, y)
      y += 4.5
    })
  }

  const bullet = (text: string) => {
    checkPage(5)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(180, 180, 180)
    const lines = doc.splitTextToSize(text, contentW - 6)
    doc.text('•', margin + 1, y)
    lines.forEach((line: string, i: number) => {
      checkPage(5)
      doc.text(line, margin + 5, y)
      if (i < lines.length - 1) y += 4.5
    })
    y += 4.5
  }

  const gap = (n = 4) => { y += n }

  // ── Cover page ──────────────────────────────────────────
  doc.setFillColor(28, 28, 28)
  doc.rect(0, 0, pageW, pageH, 'F')

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 229, 158)
  doc.text('AI System Blueprint', pageW / 2, 70, { align: 'center' })

  doc.setFontSize(16)
  doc.setTextColor(240, 240, 240)
  doc.text(companyName, pageW / 2, 84, { align: 'center' })

  if (blueprint.organization?.industry) {
    doc.setFontSize(10)
    doc.setTextColor(150, 150, 150)
    doc.text(blueprint.organization.industry, pageW / 2, 93, { align: 'center' })
  }

  doc.setDrawColor(0, 229, 158)
  doc.setLineWidth(0.5)
  doc.line(margin + 20, 100, pageW - margin - 20, 100)

  doc.setFontSize(9)
  doc.setTextColor(130, 130, 130)
  doc.text(`Version: ${versionLabel}`, pageW / 2, 110, { align: 'center' })
  doc.text(`AI Readiness Score: ${diagnostic_summary?.ai_readiness_score ?? '—'}  |  ${diagnostic_summary?.maturity_level ?? ''}`, pageW / 2, 117, { align: 'center' })
  doc.text(`Generated: ${date}`, pageW / 2, 124, { align: 'center' })

  addFooter()
  doc.addPage()
  pageNum++
  y = margin

  // ── 1. Strategic Objective ──────────────────────────────
  h1('1. Strategic Objective')
  if (strategic_objective?.primary_goal) {
    body(strategic_objective.primary_goal)
    gap()
  }
  if (Array.isArray(strategic_objective?.kpi_targets) && strategic_objective.kpi_targets.length > 0) {
    h2('KPI Targets')
    strategic_objective.kpi_targets.forEach(kpi => {
      bullet(`${kpi.metric}: ${kpi.target}`)
    })
  }
  gap(6)

  // ── 2. System Architecture ──────────────────────────────
  h1('2. System Architecture')
  if (Array.isArray(system_architecture?.data_sources) && system_architecture.data_sources.length > 0) {
    h2('Data Sources')
    system_architecture.data_sources.forEach(s => bullet(s))
    gap()
  }
  if (Array.isArray(system_architecture?.processing_layers) && system_architecture.processing_layers.length > 0) {
    h2('Processing Layers')
    system_architecture.processing_layers.forEach(s => bullet(s))
    gap()
  }
  if (system_architecture?.decision_engine) {
    h2('Decision Engine')
    body(system_architecture.decision_engine)
    gap()
  }
  if (Array.isArray(system_architecture?.execution_layer) && system_architecture.execution_layer.length > 0) {
    h2('Execution Layer')
    system_architecture.execution_layer.forEach(s => bullet(s))
    gap()
  }
  if (system_architecture?.memory_layer) {
    h2('Memory Layer')
    body(system_architecture.memory_layer)
  }
  gap(6)

  // ── 3. Workflow Modules ─────────────────────────────────
  h1('3. Workflow Modules')
  if (Array.isArray(workflow_modules)) {
    workflow_modules.forEach((wf, i) => {
      checkPage(16)
      h2(`${i + 1}. ${wf.name}`)
      body(`Trigger: ${wf.trigger}`)
      if (Array.isArray(wf.steps)) {
        wf.steps.forEach((step, j) => bullet(`Step ${j + 1} [${step.type}]: ${step.action}`))
      }
      if (Array.isArray(wf.integrations_required) && wf.integrations_required.length > 0) {
        body(`Integrations: ${wf.integrations_required.join(', ')}`, 2)
      }
      gap(4)
    })
  }
  gap(6)

  // ── 4. Risk Assessment ──────────────────────────────────
  h1('4. Risk Assessment')
  if (Array.isArray(risk_assessment?.data_risks) && risk_assessment.data_risks.length > 0) {
    h2('Data Risks')
    risk_assessment.data_risks.forEach(r => bullet(r))
    gap()
  }
  if (Array.isArray(risk_assessment?.operational_risks) && risk_assessment.operational_risks.length > 0) {
    h2('Operational Risks')
    risk_assessment.operational_risks.forEach(r => bullet(r))
    gap()
  }
  if (Array.isArray(risk_assessment?.mitigation_strategies) && risk_assessment.mitigation_strategies.length > 0) {
    h2('Mitigation Strategies')
    risk_assessment.mitigation_strategies.forEach((s, i) => bullet(`${i + 1}. ${s}`))
  }
  gap(6)

  // ── 5. Deployment Plan ──────────────────────────────────
  h1('5. Deployment Plan')
  if (deployment_plan?.phase) body(`Phase: ${deployment_plan.phase}`)
  if (deployment_plan?.estimated_impact) body(`Estimated Impact: ${deployment_plan.estimated_impact}`)
  if (deployment_plan?.estimated_roi_months) body(`ROI Timeline: ${deployment_plan.estimated_roi_months} months`)
  if (Array.isArray(deployment_plan?.waves) && deployment_plan.waves.length > 0) {
    gap(4)
    h2('Deployment Waves')
    deployment_plan.waves.forEach(wave => {
      checkPage(12)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(200, 200, 200)
      doc.text(wave.name, margin + 2, y)
      y += 4.5
      if (Array.isArray(wave.included_workflows) && wave.included_workflows.length > 0) {
        body(`Workflows: ${wave.included_workflows.join(', ')}`, 4)
      }
      if (wave.notes) body(wave.notes, 4)
      gap(3)
    })
  }

  addFooter()
  doc.save(`Aivory-Blueprint-${safeFilename(companyName)}-${versionLabel}-${date}.pdf`)
}

// ── DOCX export ───────────────────────────────────────────
export async function exportBlueprintDOCX(
  blueprint: BlueprintV1,
  versionLabel: string
) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } = await import('docx')
  const { saveAs } = await import('file-saver')

  const companyName = blueprint.organization?.name || 'Company'
  const date = dateStr()
  const { strategic_objective, system_architecture, workflow_modules, risk_assessment, deployment_plan } = blueprint

  const h1 = (text: string) => new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 320, after: 120 } })
  const h2 = (text: string) => new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 80 } })
  const body = (text: string) => new Paragraph({ children: [new TextRun({ text, size: 22 })], spacing: { after: 80 } })
  const bullet = (text: string) => new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 60 } })
  const divider = () => new Paragraph({ text: '', spacing: { after: 120 } })

  const noBorder = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }

  const sections: InstanceType<typeof Paragraph>[] = []

  // Title
  sections.push(new Paragraph({
    children: [new TextRun({ text: `AI System Blueprint — ${companyName}`, bold: true, size: 36, color: '00e59e' })],
    spacing: { after: 80 },
  }))
  sections.push(body(`Version: ${versionLabel}  |  Generated by Aivory  |  ${date}`))
  sections.push(divider())

  // 1. Strategic Objective
  sections.push(h1('1. Strategic Objective'))
  if (strategic_objective?.primary_goal) sections.push(body(strategic_objective.primary_goal))
  if (Array.isArray(strategic_objective?.kpi_targets) && strategic_objective.kpi_targets.length > 0) {
    sections.push(h2('KPI Targets'))
    const rows = [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Metric', bold: true })] })], borders: { bottom: { style: BorderStyle.SINGLE, size: 1, color: '444444' }, top: noBorder, left: noBorder, right: noBorder } }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Target', bold: true })] })], borders: { bottom: { style: BorderStyle.SINGLE, size: 1, color: '444444' }, top: noBorder, left: noBorder, right: noBorder } }),
        ]
      }),
      ...strategic_objective.kpi_targets.map(kpi => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(kpi.metric)], borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder } }),
          new TableCell({ children: [new Paragraph(kpi.target)], borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder } }),
        ]
      }))
    ]
    sections.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }) as unknown as InstanceType<typeof Paragraph>)
  }
  sections.push(divider())

  // 2. System Architecture
  sections.push(h1('2. System Architecture'))
  if (Array.isArray(system_architecture?.data_sources)) {
    sections.push(h2('Data Sources'))
    system_architecture.data_sources.forEach(s => sections.push(bullet(s)))
  }
  if (Array.isArray(system_architecture?.processing_layers)) {
    sections.push(h2('Processing Layers'))
    system_architecture.processing_layers.forEach(s => sections.push(bullet(s)))
  }
  if (system_architecture?.decision_engine) {
    sections.push(h2('Decision Engine'))
    sections.push(body(system_architecture.decision_engine))
  }
  if (Array.isArray(system_architecture?.execution_layer)) {
    sections.push(h2('Execution Layer'))
    system_architecture.execution_layer.forEach(s => sections.push(bullet(s)))
  }
  if (system_architecture?.memory_layer) {
    sections.push(h2('Memory Layer'))
    sections.push(body(system_architecture.memory_layer))
  }
  sections.push(divider())

  // 3. Workflow Modules
  sections.push(h1('3. Workflow Modules'))
  if (Array.isArray(workflow_modules)) {
    workflow_modules.forEach((wf, i) => {
      sections.push(h2(`${i + 1}. ${wf.name}`))
      sections.push(body(`Trigger: ${wf.trigger}`))
      if (Array.isArray(wf.steps)) {
        wf.steps.forEach((step, j) => sections.push(bullet(`Step ${j + 1} [${step.type}]: ${step.action}`)))
      }
      if (Array.isArray(wf.integrations_required) && wf.integrations_required.length > 0) {
        sections.push(body(`Integrations: ${wf.integrations_required.join(', ')}`))
      }
    })
  }
  sections.push(divider())

  // 4. Risk Assessment
  sections.push(h1('4. Risk Assessment'))
  if (Array.isArray(risk_assessment?.data_risks)) {
    sections.push(h2('Data Risks'))
    risk_assessment.data_risks.forEach(r => sections.push(bullet(r)))
  }
  if (Array.isArray(risk_assessment?.operational_risks)) {
    sections.push(h2('Operational Risks'))
    risk_assessment.operational_risks.forEach(r => sections.push(bullet(r)))
  }
  if (Array.isArray(risk_assessment?.mitigation_strategies)) {
    sections.push(h2('Mitigation Strategies'))
    risk_assessment.mitigation_strategies.forEach((s, i) => sections.push(bullet(`${i + 1}. ${s}`)))
  }
  sections.push(divider())

  // 5. Deployment Plan
  sections.push(h1('5. Deployment Plan'))
  if (deployment_plan?.phase) sections.push(body(`Phase: ${deployment_plan.phase}`))
  if (deployment_plan?.estimated_impact) sections.push(body(`Estimated Impact: ${deployment_plan.estimated_impact}`))
  if (deployment_plan?.estimated_roi_months) sections.push(body(`ROI Timeline: ${deployment_plan.estimated_roi_months} months`))
  if (Array.isArray(deployment_plan?.waves)) {
    sections.push(h2('Deployment Waves'))
    deployment_plan.waves.forEach(wave => {
      sections.push(new Paragraph({ children: [new TextRun({ text: wave.name, bold: true, size: 22 })], spacing: { before: 120, after: 40 } }))
      if (Array.isArray(wave.included_workflows)) sections.push(body(`Workflows: ${wave.included_workflows.join(', ')}`))
      if (wave.notes) sections.push(body(wave.notes))
    })
  }
  sections.push(divider())

  // Footer
  sections.push(new Paragraph({
    children: [new TextRun({ text: `Generated by Aivory  |  ${date}  |  ${versionLabel}`, color: '888888', size: 18, italics: true })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 240 },
  }))

  const doc = new Document({
    sections: [{ properties: {}, children: sections }],
    styles: {
      default: {
        document: { run: { font: 'Calibri', size: 22, color: '222222' } },
      }
    }
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `Aivory-Blueprint-${safeFilename(companyName)}-${date}.docx`)
}
