const express = require('express');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const app = express();
app.use(express.json({ limit: '1mb' }));

const WORKFLOW_STORE = process.env.WORKFLOW_STORE || '/opt/workflows-store';
loadEnvFile(path.join(WORKFLOW_STORE, '.env'));

const DRAFTS_DIR = path.join(WORKFLOW_STORE, 'drafts');
const N8N_HOST = (process.env.N8N_HOST || 'http://localhost:5678').replace(/\/$/, '');
const N8N_API_KEY = process.env.N8N_API_KEY || '';

// Structured JSON logging
const logInfo = (data) => {
  console.log(JSON.stringify({
    level: 'info',
    service: 'n8n-as-code-service',
    ts: new Date().toISOString(),
    ...data,
  }));
};

const logError = (data) => {
  console.error(JSON.stringify({
    level: 'error',
    service: 'n8n-as-code-service',
    ts: new Date().toISOString(),
    ...data,
  }));
};

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) continue;
    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim().replace(/^["']|["']$/g, '');
    if (key && process.env[key] === undefined) process.env[key] = value;
  }
}

function ensureDraftsDir() {
  fs.mkdirSync(DRAFTS_DIR, { recursive: true });
}

function buildDraftId(value) {
  return value || `draft_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
}

function safeFileName(value) {
  return String(value).replace(/[^a-zA-Z0-9_-]/g, '_');
}

function draftPaths(draftId) {
  const safeId = safeFileName(draftId);
  return {
    workflowPath: path.join(DRAFTS_DIR, `${safeId}.workflow.ts`),
    metaPath: path.join(DRAFTS_DIR, `${safeId}.meta.json`),
  };
}

function normalizeSteps(steps) {
  if (!Array.isArray(steps)) return [];
  return steps.map((step, index) => ({
    id: step.id || `step_${index + 1}`,
    type: step.type || (index === 0 ? 'trigger' : 'action'),
    title: step.title || step.action || `Step ${index + 1}`,
    description: step.description || step.output || '',
    nodeType: step.nodeType || null,
    parameters: step.parameters || {},
    typeVersion: step.typeVersion || null,
    config: step.config || {},
    n8nInspection: step.n8nInspection || null,
  }));
}

function buildWorkflowCode({ draftId, intent, steps, config }) {
  const payload = {
    draftId,
    intent,
    generatedAt: new Date().toISOString(),
    source: 'aivory-n8n-as-code-service',
    steps,
    config: config || {},
  };

  return [
    '// Auto-generated by Aivory Workflow Copilot',
    '// This draft is validated in the sandbox before user activation.',
    '',
    `export default ${JSON.stringify(payload, null, 2)};`,
    '',
  ].join('\n');
}

const NODE_TYPE_MAP = {
  schedule: {
    type: 'n8n-nodes-base.scheduleTrigger',
    typeVersion: 1.1,
    parameters: {
      rule: { interval: [{ field: 'hours', hoursInterval: 24 }] },
    },
  },
  email: {
    type: 'n8n-nodes-base.emailSend',
    typeVersion: 2.1,
    parameters: {
      fromEmail: '',
      toEmail: '',
      subject: 'Aivory Automated Email',
      message: '',
    },
  },
  database: {
    type: 'n8n-nodes-base.mySql',
    typeVersion: 2.4,
    parameters: { operation: 'executeQuery', query: '' },
  },
  http: {
    type: 'n8n-nodes-base.httpRequest',
    typeVersion: 4.2,
    parameters: { method: 'GET', url: '' },
  },
  ssh: {
    type: 'n8n-nodes-base.ssh',
    typeVersion: 1,
    parameters: { operation: 'executeCommand', command: '' },
  },
  ftp: {
    type: 'n8n-nodes-base.ftp',
    typeVersion: 1,
    parameters: { operation: 'list', path: '/' },
  },
  compress: {
    type: 'n8n-nodes-base.executeCommand',
    typeVersion: 1,
    parameters: { command: 'tar -czf output.tar.gz ./input' },
  },
  cleanup: {
    type: 'n8n-nodes-base.executeCommand',
    typeVersion: 1,
    parameters: { command: 'rm -rf /tmp/aivory-temp/*' },
  },
  filter: {
    type: 'n8n-nodes-base.if',
    typeVersion: 2,
    parameters: { conditions: { options: {}, conditions: [] } },
  },
  transform: {
    type: 'n8n-nodes-base.set',
    typeVersion: 3.4,
    parameters: { mode: 'manual', assignments: { assignments: [] } },
  },
  messaging: {
    type: 'n8n-nodes-base.slack',
    typeVersion: 2.2,
    parameters: { operation: 'message', channel: '', text: '' },
  },
  respond: {
    type: 'n8n-nodes-base.respondToWebhook',
    typeVersion: 1.1,
    parameters: { respondWith: 'text', responseBody: 'OK' },
  },
  webhook: {
    type: 'n8n-nodes-base.webhook',
    typeVersion: 2,
    parameters: { httpMethod: 'POST', path: 'aivory-webhook', responseMode: 'onReceived' },
  },
  trigger: {
    type: 'n8n-nodes-base.manualTrigger',
    typeVersion: 1,
    parameters: {},
  },
  ai: {
    type: 'n8n-nodes-base.httpRequest',
    typeVersion: 4.2,
    parameters: {
      method: 'POST',
      url: process.env.ZEROCLAW_URL || 'http://localhost:3010/api/chat',
      sendBody: true,
      bodyParameters: { parameters: [{ name: 'message', value: '' }] },
    },
  },
  default: {
    type: 'n8n-nodes-base.set',
    typeVersion: 3.4,
    parameters: { mode: 'manual', assignments: { assignments: [] } },
  },
};

function detectIntent(stepTitle, stepType, stepDescription) {
  const text = `${stepTitle} ${stepType} ${stepDescription || ''}`.toLowerCase();

  const PATTERNS = {
    schedule:  /schedule|cron|daily|hourly|weekly|timer|interval|every\s+\d|jadwal|setiap|berkala|per\s*\d+\s*jam|tiap/,
    email:     /email|mail\b|smtp|inbox|send.*mail/,
    database:  /mysql|postgres|postgresql|sql\b|database|db\b|query|select|insert/,
    http:      /\bhttp\b|\bapi\b|request\b|fetch\b|call.*endpoint|rest\b|post.*url|get.*url/,
    ssh:       /\bssh\b|\bscp\b|\bexec\b|remote.*command|run.*command|shell\b/,
    ftp:       /ftp|sftp|file.*transfer|upload.*file|download.*file/,
    compress:  /compress|zip\b|tar\b|gzip|archive|unzip|extract/,
    cleanup:   /delete\b|remove\b|cleanup|clean.*up|purge\b|clear\b|truncate/,
    filter:    /condition|\bif\b|decision|\bcheck\b|\bfilter\b|branch/,
    transform: /transform|convert|format\b|parse\b|extract\b|set.*value|map.*data/,
    messaging: /slack|discord|telegram|whatsapp|\bsms\b|\bteams\b/,
    respond:   /\brespond\b|\breturn\b|send.*response|reply\b|webhook.*response/,
    webhook:   /webhook|trigger.*http|http.*trigger|on.*request/,
    ai:        /\bai\b|\bllm\b|analyze|generate\b|summarize|classify|\bgpt\b|zeroclaw/,
  };

  // stepType exact match first
  if (stepType && PATTERNS[stepType]) return stepType;

  // Pattern match on full text
  for (const [intent, pattern] of Object.entries(PATTERNS)) {
    if (pattern.test(text)) return intent;
  }

  // Fallback: first step = trigger, rest = transform
  return 'default';
}

function buildRealN8nWorkflow({ draftId, intent, steps }) {
  const nodes      = [];
  const connections = {};
  const GRID_X     = 280;  // horizontal spacing between nodes
  const START_X    = 100;
  const START_Y    = 300;

  // If no steps or empty, fallback to manual trigger only
  if (!steps || steps.length === 0) {
    return {
      name: `Aivory Draft ${draftId}`,
      settings: {},
      nodes: [
        {
          id: 'ManualTrigger_1',
          name: 'Manual Trigger',
          type: 'n8n-nodes-base.manualTrigger',
          typeVersion: 1,
          position: [START_X, START_Y],
          parameters: {},
        },
      ],
      connections: {},
    };
  }

  // Build nodes from steps
  steps.forEach((step, index) => {
    // Use nodeType from step if provided (from ZeroClaw/n8n MCP inspection)
    // Fall back to detectIntent only if nodeType is not available
    let nodeConfig;
    let intent;
    if (step.nodeType) {
      // Direct n8n node type provided — use it directly
      nodeConfig = {
        type: step.nodeType,
        typeVersion: step.typeVersion || 1,
        parameters: step.parameters || {},
      };
      intent = 'direct';
    } else {
      intent = detectIntent(
        step.title || step.action || '',
        step.type  || '',
        step.description || ''
      );
      nodeConfig = NODE_TYPE_MAP[intent] || NODE_TYPE_MAP.default;
    }
    const nodeName   = step.title || `Step ${index + 1}`;
    const nodeId     = `node_${index + 1}_${intent}`;

    nodes.push({
      id:          nodeId,
      name:        nodeName,
      type:        nodeConfig.type,
      typeVersion: nodeConfig.typeVersion,
      position:    [START_X + (index * GRID_X), START_Y],
      parameters:  { ...nodeConfig.parameters },
    });
  });

  // Auto-wire connections: each node output → next node input
  for (let i = 0; i < nodes.length - 1; i++) {
    const fromName = nodes[i].name;
    const toName   = nodes[i + 1].name;

    connections[fromName] = {
      main: [[{ node: toName, type: 'main', index: 0 }]],
    };
  }

  return {
    name:        intent || `Aivory Workflow ${draftId}`,
    settings:    {},
    nodes,
    connections,
  };
}

async function n8nApiRequest(method, apiPath, body) {
  const url = `${N8N_HOST}/api/v1${apiPath}`;
  const headers = { 'Content-Type': 'application/json' };
  if (N8N_API_KEY) headers['X-N8N-API-KEY'] = N8N_API_KEY;

  const response = await fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  const text = await response.text();
  if (!response.ok) {
    const error = new Error(text.trim() || `${method} ${apiPath} failed`);
    error.status = response.status;
    throw error;
  }

  try {
    return text ? JSON.parse(text) : null;
  } catch {
    return text;
  }
}

function readMeta(draftId) {
  const { metaPath } = draftPaths(draftId);
  if (!fs.existsSync(metaPath)) {
    const error = new Error('draft not found');
    error.status = 404;
    throw error;
  }
  return JSON.parse(fs.readFileSync(metaPath, 'utf8'));
}

function writeMeta(draftId, meta) {
  const { metaPath } = draftPaths(draftId);
  fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2));
}

function inferNodeRequirement(step) {
  const title = step.title || step.action || step.nodeName || step.id || 'Workflow Step';
  const description = step.description || step.output || '';
  const haystack = `${title} ${description}`.toLowerCase();
  const inspectedNode = step.n8nInspection?.selectedNode;

  const definitions = [
    {
      match: /(email|smtp|mail|newsletter)/,
      nodeName: 'Email Delivery',
      nodeType: 'n8n-nodes-base.emailSend',
      credentialType: 'smtpCredentials',
      requiredFields: [
        { key: 'host', label: 'SMTP Host', type: 'text', example: 'smtp.gmail.com' },
        { key: 'port', label: 'SMTP Port', type: 'text', example: '465' },
        { key: 'user', label: 'SMTP Username', type: 'text', example: 'automation@company.com' },
        { key: 'password', label: 'SMTP Password / App Password', type: 'password' },
      ],
    },
    {
      match: /(slack)/,
      nodeName: 'Slack',
      nodeType: 'n8n-nodes-base.slack',
      credentialType: 'slackApi',
      requiredFields: [{ key: 'botToken', label: 'Slack Bot Token', type: 'password' }],
    },
    {
      match: /(notion)/,
      nodeName: 'Notion',
      nodeType: 'n8n-nodes-base.notion',
      credentialType: 'notionApi',
      requiredFields: [{ key: 'apiKey', label: 'Notion Internal Integration Token', type: 'password' }],
    },
    {
      match: /(crm|hubspot|salesforce|pipedrive)/,
      nodeName: 'CRM',
      nodeType: 'n8n-nodes-base.httpRequest',
      credentialType: 'httpHeaderAuth',
      requiredFields: [
        { key: 'baseUrl', label: 'CRM Base URL', type: 'text', example: 'https://api.hubapi.com' },
        { key: 'apiKey', label: 'CRM API Key / Token', type: 'password' },
      ],
    },
    {
      match: /(sheet|spreadsheet|google sheet|sheets)/,
      nodeName: 'Google Sheets',
      nodeType: 'n8n-nodes-base.googleSheets',
      credentialType: 'googleSheetsOAuth2Api',
      requiredFields: [{ key: 'oauth', label: 'Google Sheets OAuth', type: 'oauth' }],
    },
    {
      match: /(http|api|webhook|rest)/,
      nodeName: 'HTTP Request',
      nodeType: 'n8n-nodes-base.httpRequest',
      credentialType: 'httpHeaderAuth',
      requiredFields: [
        { key: 'baseUrl', label: 'API Base URL', type: 'text', example: 'https://api.example.com' },
        { key: 'apiKey', label: 'API Key / Bearer Token', type: 'password' },
      ],
    },
  ];

  const matched = definitions.find((definition) => definition.match.test(haystack));
  if (!matched && inspectedNode && step.n8nInspection?.schema?.credentials) {
    return {
      nodeId: step.id || title.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
      nodeName: inspectedNode.displayName || title,
      nodeType: inspectedNode.workflowNodeType || inspectedNode.nodeType || 'unknown',
      credentialType: step.n8nInspection?.schema?.credentials ? 'credential_required' : undefined,
      requiredFields: [],
    };
  }
  if (!matched) return null;

  return {
    nodeId: step.id || title.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
    nodeName: matched.nodeName,
    nodeType: matched.nodeType,
    credentialType: matched.credentialType,
    requiredFields: matched.requiredFields,
  };
}

function buildSetupReport(meta) {
  const nodeRequirements = meta.steps.map(inferNodeRequirement).filter(Boolean);
  return {
    workflowId: meta.draftId,
    workflowName: meta.intent || 'Aivory Workflow Draft',
    readyToDeploy: nodeRequirements.length === 0,
    nodeRequirements,
    summary: nodeRequirements.length === 0
      ? 'No external credentials were inferred from the current draft.'
      : `This draft needs ${nodeRequirements.length} credential or configuration setup item(s) before activation.`,
  };
}

app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

app.post('/drafts/build', (req, res) => {
  try {
    const { session_id, draft_id, intent, steps, config } = req.body || {};
    
    logInfo({ event: 'request', path: '/drafts/build', session_id });
    
    const normalizedSteps = normalizeSteps(steps);
    if (!intent || typeof intent !== 'string') {
      return res.status(400).json({
        error: {
          code: 'INVALID_WORKFLOW_SPEC',
          message: 'intent is required',
          source: 'n8n-as-code-service'
        }
      });
    }
    if (normalizedSteps.length === 0) {
      return res.status(400).json({
        error: {
          code: 'INVALID_WORKFLOW_SPEC',
          message: 'steps must be a non-empty array',
          source: 'n8n-as-code-service'
        }
      });
    }

    ensureDraftsDir();
    const resolvedDraftId = buildDraftId(draft_id || session_id);
    const { workflowPath } = draftPaths(resolvedDraftId);
    const meta = {
      draftId: resolvedDraftId,
      sessionId: session_id || null,
      intent,
      steps: normalizedSteps,
      config: config || {},
      status: 'draft_created',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    fs.writeFileSync(workflowPath, buildWorkflowCode({
      draftId: resolvedDraftId,
      intent,
      steps: normalizedSteps,
      config,
    }));
    writeMeta(resolvedDraftId, meta);

    logInfo({ event: 'success', path: '/drafts/build', status: 'ok', draftId: resolvedDraftId });

    res.json({
      draft_id: resolvedDraftId,
      workflow_code_path: workflowPath,
      nodes_count: normalizedSteps.length,
      state: 'draft_created',
    });
  } catch (error) {
    logError({
      event: 'error',
      path: '/drafts/build',
      error_message: error.message
    });
    res.status(error.status || 500).json({ error: true, message: error.message });
  }
});

// =============================================================
// CREDENTIAL BINDING HELPERS
// =============================================================

async function n8nFetchCredentials() {
  const n8nHost = process.env.N8N_HOST    || 'http://localhost:5678';
  const apiKey  = process.env.N8N_API_KEY || '';
  const res = await fetch(`${n8nHost}/api/v1/credentials`, {
    headers: { 'X-N8N-API-KEY': apiKey },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch credentials (${res.status}): ${await res.text()}`);
  }
  const data = await res.json();
  // n8n returns { data: [...] } or directly [...]
  return Array.isArray(data) ? data : (data?.data || []);
}

function matchCredentialToNode(nodeType, availableCredentials) {
  // Map n8n node type → credential type string
  const NODE_TO_CRED = {
    'n8n-nodes-base.mySql':           'mySqlApi',
    'n8n-nodes-base.postgres':        'postgresApi',
    'n8n-nodes-base.emailSend':       'smtpCredentials',
    'n8n-nodes-base.ssh':             'sshPassword',
    'n8n-nodes-base.ftp':             'ftpCredentials',
    'n8n-nodes-base.slack':           'slackApi',
    'n8n-nodes-base.notion':          'notionApi',
    'n8n-nodes-base.googleSheets':    'googleSheetsOAuth2Api',
    'n8n-nodes-base.httpRequest':     'httpHeaderAuth',
    'n8n-nodes-base.webhook':         null,           // no credential needed
    'n8n-nodes-base.manualTrigger':   null,
    'n8n-nodes-base.scheduleTrigger': null,
    'n8n-nodes-base.set':             null,
    'n8n-nodes-base.if':              null,
    'n8n-nodes-base.executeCommand':  null,
  };

  const expectedCredType = NODE_TO_CRED[nodeType];
  if (expectedCredType === null) return { required: false };
  if (expectedCredType === undefined) return { required: true, credentialType: 'unknown', matched: null };

  const matched = availableCredentials.find(c => c.type === expectedCredType);
  return {
    required: true,
    credentialType: expectedCredType,
    matched: matched ? { id: matched.id, name: matched.name, type: matched.type } : null,
  };
}

function buildCredentialBindings(workflowNodes, availableCredentials) {
  const bindings  = [];
  const missing   = [];

  for (const node of workflowNodes) {
    const result = matchCredentialToNode(node.type, availableCredentials);
    if (!result.required) continue;

    if (result.matched) {
      bindings.push({
        nodeId:         node.id,
        nodeName:       node.name,
        nodeType:       node.type,
        credentialId:   result.matched.id,
        credentialName: result.matched.name,
        credentialType: result.credentialType,
        status:         'bound',
      });
    } else {
      missing.push({
        nodeId:         node.id,
        nodeName:       node.name,
        nodeType:       node.type,
        credentialType: result.credentialType,
        status:         'missing',
        action:         `Create a "${result.credentialType}" credential in n8n for this node`,
      });
    }
  }

  return { bindings, missing };
}

function injectCredentialsIntoWorkflow(workflowDef, bindings) {
  // Deep clone to avoid mutating original
  const wf = JSON.parse(JSON.stringify(workflowDef));

  for (const node of wf.nodes) {
    const binding = bindings.find(b => b.nodeId === node.id || b.nodeName === node.name);
    if (!binding) continue;

    // n8n credential format on node:
    // credentials: { mySqlApi: { id: "123", name: "my-mysql-cred" } }
    node.credentials = node.credentials || {};
    node.credentials[binding.credentialType] = {
      id:   String(binding.credentialId),
      name: binding.credentialName,
    };
  }

  return wf;
}

// =============================================================
// REAL EXECUTION SANDBOX HELPERS — injected by Task 3
// =============================================================

async function n8nLogin() {
  const n8nHost  = process.env.N8N_HOST          || 'http://localhost:5678';
  const email    = process.env.N8N_ADMIN_EMAIL    || 'admin@aivory.local';
  const password = process.env.N8N_ADMIN_PASSWORD || 'Aivory2026!';
  const res = await fetch(`${n8nHost}/rest/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ emailOrLdapLoginId: email, password }),
  });
  if (!res.ok) throw new Error(`Login failed (${res.status}): ${await res.text()}`);
  let rawCookies = [];
  if (typeof res.headers.raw === 'function') {
    rawCookies = res.headers.raw()['set-cookie'] || [];
  } else {
    const sc = res.headers.get('set-cookie');
    if (sc) rawCookies = [sc];
  }
  if (!rawCookies.length) throw new Error('Login OK but no Set-Cookie header returned');
  return rawCookies.map(c => c.split(';')[0].trim()).join('; ');
}

async function n8nFetchWorkflow(workflowId) {
  const n8nHost = process.env.N8N_HOST    || 'http://localhost:5678';
  const apiKey  = process.env.N8N_API_KEY || '';
  const res = await fetch(`${n8nHost}/api/v1/workflows/${workflowId}`, {
    headers: { 'X-N8N-API-KEY': apiKey },
  });
  if (!res.ok) throw new Error(`Fetch workflow failed (${res.status}): ${await res.text()}`);
  return res.json();
}

async function n8nRunWorkflow(workflowId, workflowData, cookie) {
  const n8nHost = process.env.N8N_HOST || 'http://localhost:5678';
  const nodes   = workflowData.nodes || [];
  
  // Safer trigger detection with priority order
  const TRIGGER_PRIORITY = [
    'n8n-nodes-base.manualTrigger',
    'n8n-nodes-base.scheduleTrigger',
    'n8n-nodes-base.webhook',
    'n8n-nodes-base.webhookTrigger',
  ];
  
  const trigger = TRIGGER_PRIORITY.reduce((found, type) =>
    found ?? nodes.find(n => n.type === type), null
  ) ?? nodes.find(n =>
    n.type?.toLowerCase().includes('trigger') &&
    !n.type?.toLowerCase().includes('error')
  ) ?? nodes[0];
  const res = await fetch(`${n8nHost}/rest/workflows/${workflowId}/run`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Cookie': cookie },
    body: JSON.stringify({
      startNodes:      [trigger?.name || 'Manual Trigger'],
      destinationNode: '',
      runData:         null,
      pinData:         {},
      workflowData:    workflowData,
    }),
  });
  if (!res.ok) throw new Error(`Run failed (${res.status}): ${await res.text()}`);
  const data = await res.json();
  const executionId = data?.data?.executionId ?? data?.executionId;
  if (!executionId) throw new Error(`No executionId in response: ${JSON.stringify(data)}`);
  return String(executionId);
}

async function n8nPollExecution(executionId, cookie) {
  const n8nHost  = process.env.N8N_HOST || 'http://localhost:5678';
  const deadline = Date.now() + 30000;
  while (Date.now() < deadline) {
    const res  = await fetch(`${n8nHost}/rest/executions/${executionId}`, {
      headers: { 'Cookie': cookie },
    });
    if (!res.ok) throw new Error(`Poll failed (${res.status})`);
    const exec = (await res.json())?.data;
    
    // Handle non-recoverable states
    if (exec?.status === 'waiting') {
      // Workflow paused at a Wait node — treat as partial success
      exec.finished = true;
    }
    if (exec?.status === 'crashed' || exec?.status === 'canceled') {
      // Non-recoverable — exit immediately with error
      throw new Error(`Execution ${exec.status}: workflow did not complete`);
    }
    
    if (exec?.finished === true) return exec;
    await new Promise(r => setTimeout(r, 1000));
  }
  throw new Error('Timeout: execution did not finish in 30 seconds');
}

function deserializeN8nRunData(dataStr) {
  if (!dataStr || typeof dataStr !== 'string') return null;
  try {
    const arr     = JSON.parse(dataStr);
    if (!Array.isArray(arr)) return null;
    const resolve = v => (typeof v === 'string' && /^\d+$/.test(v) && +v < arr.length)
      ? arr[+v] : v;
    const runDataMap = resolve(resolve(resolve(arr[0])?.resultData)?.runData);
    if (!runDataMap || typeof runDataMap !== 'object') return null;
    const out = {};
    for (const [name, ref] of Object.entries(runDataMap)) {
      const run    = resolve(ref);
      if (!run) continue;
      const status = resolve(run.executionStatus) || 'unknown';
      const errRaw = run.error ? resolve(run.error) : null;
      out[name] = {
        status,
        executionTime: run.executionTime ?? null,
        ...(errRaw && { error: typeof errRaw === 'string' ? errRaw : errRaw?.message ?? JSON.stringify(errRaw) }),
      };
    }
    return Object.keys(out).length ? out : null;
  } catch { return null; }
}

function stripCredentialsForSandbox(workflowDef) {
  // Deep clone
  const wf = JSON.parse(JSON.stringify(workflowDef));

  // Nodes that need credential stripping — replace with Set node
  // so n8n can execute without credential errors
  const CREDENTIAL_NODE_TYPES = [
    'n8n-nodes-base.mySql',
    'n8n-nodes-base.postgres',
    'n8n-nodes-base.emailSend',
    'n8n-nodes-base.ssh',
    'n8n-nodes-base.ftp',
    'n8n-nodes-base.slack',
    'n8n-nodes-base.notion',
    'n8n-nodes-base.googleSheets',
  ];

  wf.nodes = wf.nodes.map(node => {
    // Remove any credential fields
    const stripped = { ...node };
    delete stripped.credentials;

    // If node requires credentials, swap to a harmless Set node
    // that proves the logic flow works without credential errors
    if (CREDENTIAL_NODE_TYPES.includes(node.type)) {
      return {
        id:          stripped.id,
        name:        stripped.name,
        type:        'n8n-nodes-base.set',
        typeVersion: 3.4,
        position:    stripped.position,
        parameters: {
          mode: 'manual',
          assignments: {
            assignments: [{
              id:    '1',
              name:  'sandbox_note',
              value: `[SANDBOX] ${node.name} — requires credential in production`,
              type:  'string',
            }]
          },
        },
      };
    }

    return stripped;
  });

  return wf;
}

async function runSandboxTest(workflowDefinition) {
  const n8nHost = process.env.N8N_HOST    || 'http://localhost:5678';
  const apiKey  = process.env.N8N_API_KEY || '';
  const logs    = [];
  let   wfId    = null;
  const log     = m => { logs.push(m); console.log(`[sandbox] ${m}`); };

  try {
    log('Creating sandbox workflow...');
    // Strip credentials so n8n can execute logic without credential errors
    // Credential validation is done separately via /drafts/bind-credentials
    const sandboxWorkflow = stripCredentialsForSandbox(workflowDefinition);
    log(`Stripped credentials from ${sandboxWorkflow.nodes.length} nodes for sandbox`);
    const cr = await fetch(`${n8nHost}/api/v1/workflows`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-N8N-API-KEY': apiKey },
      body: JSON.stringify({
        ...sandboxWorkflow,
        settings: { ...(sandboxWorkflow.settings ?? {}), executionOrder: 'v1' },
      }),
    });
    if (!cr.ok) throw new Error(`Create failed (${cr.status}): ${await cr.text()}`);
    wfId = String((await cr.json())?.id ?? '');
    if (!wfId) throw new Error('No workflow ID returned from create');
    log(`Created: ${wfId}`);

    log('Logging in to n8n...');
    const cookie = await n8nLogin();
    log('Login OK');

    log('Fetching full workflow data (required for /run)...');
    const wfData = await n8nFetchWorkflow(wfId);
    log(`Fetched: ${wfData.nodes?.length} nodes`);

    log('Triggering execution...');
    const execId = await n8nRunWorkflow(wfId, wfData, cookie);
    log(`Execution started: ${execId}`);

    log('Waiting for result (max 30s)...');
    const exec = await n8nPollExecution(execId, cookie);
    log(`Finished: status=${exec.status}`);

    const runMap      = deserializeN8nRunData(exec?.data);
    const nodeResults = runMap
      ? Object.entries(runMap).map(([name, info]) => {
          // If node-level status is unknown, trust overall exec status
          const nodeStatus = (info.status && info.status !== 'unknown')
            ? (info.status === 'success' ? 'success' : 'error')
            : (exec.status === 'success' ? 'success' : 'error');
          return {
            nodeId: name, nodeName: name,
            status: nodeStatus,
            executionTime: info.executionTime ?? null,
            ...(info.error && { error: info.error }),
          };
        })
      : (exec?.workflowData?.nodes || []).map(n => ({
          nodeId: n.id, nodeName: n.name,
          status: exec.status === 'success' ? 'success' : 'error',
        }));

    nodeResults.forEach(n =>
      log(`  ${n.status === 'success' ? 'OK' : 'FAIL'} "${n.nodeName}"${n.error ? ': ' + n.error : ''}`)
    );

    // Annotate nodes that were credential-stripped in sandbox
    const credentialNodeTypes = [
      'n8n-nodes-base.mySql',
      'n8n-nodes-base.postgres',
      'n8n-nodes-base.emailSend',
      'n8n-nodes-base.ssh',
      'n8n-nodes-base.ftp',
      'n8n-nodes-base.slack',
      'n8n-nodes-base.notion',
      'n8n-nodes-base.googleSheets',
    ];
    const strippedNodeNames = (workflowDefinition.nodes || [])
      .filter(n => credentialNodeTypes.includes(n.type))
      .map(n => n.name);
    const annotatedResults = nodeResults.map(n => ({
      ...n,
      ...(strippedNodeNames.includes(n.nodeName) && {
        sandboxNote: 'credential-stripped: logic tested, credential required in production'
      })
    }));

    // DELETE must happen AFTER polling
    log(`Deleting sandbox workflow ${wfId}...`);
    await fetch(`${n8nHost}/api/v1/workflows/${wfId}`, {
      method: 'DELETE', headers: { 'X-N8N-API-KEY': apiKey },
    });
    wfId = null;
    log('Deleted');

    const passed = exec.status === 'success';
    return {
      status:         passed ? 'passed' : 'failed',
      validationMode: 'real_execution',
      executionId:    execId,
      nodeResults:    annotatedResults,
      errors: annotatedResults
        .filter(n => n.status === 'error')
        .map(n => `"${n.nodeName}": ${n.error ?? 'execution failed'}`),
      logs,
    };

  } catch (err) {
    log(`ERROR: ${err.message}`);
    if (wfId) {
      try {
        await fetch(`${n8nHost}/api/v1/workflows/${wfId}`, {
          method: 'DELETE', headers: { 'X-N8N-API-KEY': apiKey },
        });
        log('Emergency cleanup done');
      } catch (e) { log(`Emergency cleanup failed: ${e.message}`); }
    }
    return {
      status: 'error', validationMode: 'real_execution',
      nodeResults: [], errors: [err.message], logs,
    };
  }
}

// =============================================================
// END REAL EXECUTION SANDBOX HELPERS
// =============================================================

app.post('/drafts/test', async (req, res) => {
  try {
    const { draft_id } = req.body || {};
    if (!draft_id) return res.status(400).json({ error: true, message: 'draft_id is required' });

    const meta = readMeta(draft_id);
    const workflowDef = buildRealN8nWorkflow({
      draftId: meta.draftId,
      intent: meta.intent,
      steps: meta.steps,
    });

    const result = await runSandboxTest(workflowDef);

    meta.status = result.status === 'passed' ? 'test_passed' : 'test_failed';
    meta.testResult = result;
    meta.updatedAt = new Date().toISOString();
    writeMeta(draft_id, meta);

    return res.json(result);
  } catch (error) {
    res.status(error.status || 500).json({
      status: 'failed',
      errors: [{ type: 'sandbox_test_failed', message: error.message }],
      logs: [error.message],
    });
  }
});

app.post('/drafts/bind-credentials', async (req, res) => {
  try {
    const { draft_id } = req.body || {};
    if (!draft_id) return res.status(400).json({ error: true, message: 'draft_id is required' });

    const meta         = readMeta(draft_id);
    const workflowDef  = buildRealN8nWorkflow({
      draftId: meta.draftId,
      intent:  meta.intent,
      steps:   meta.steps,
    });

    const availableCreds            = await n8nFetchCredentials();
    const { bindings, missing }     = buildCredentialBindings(workflowDef.nodes, availableCreds);
    const readyToDeploy             = missing.length === 0;

    // Persist binding result to meta
    meta.credentialBindings = { bindings, missing, checkedAt: new Date().toISOString() };
    meta.updatedAt          = new Date().toISOString();
    writeMeta(draft_id, meta);

    return res.json({
      draft_id,
      readyToDeploy,
      totalNodes:      workflowDef.nodes.length,
      boundCount:      bindings.length,
      missingCount:    missing.length,
      bindings,
      missing,
      summary: readyToDeploy
        ? 'All required credentials are available. Workflow is ready to deploy.'
        : `${missing.length} credential(s) missing. Create them in n8n before deploying.`,
    });
  } catch (error) {
    res.status(error.status || 500).json({ error: true, message: error.message });
  }
});

app.post('/drafts/deploy', async (req, res) => {
  try {
    const { draft_id, activate = true } = req.body || {};
    
    logInfo({ event: 'request', path: '/drafts/deploy', draft_id });
    
    if (!draft_id) {
      return res.status(400).json({
        error: {
          code: 'INVALID_WORKFLOW_SPEC',
          message: 'draft_id is required',
          source: 'n8n-as-code-service'
        }
      });
    }

    const meta        = readMeta(draft_id);
    const workflowDef = buildRealN8nWorkflow({
      draftId: meta.draftId,
      intent:  meta.intent,
      steps:   meta.steps,
    });

    // Step 1: Get credential bindings
    const availableCreds        = await n8nFetchCredentials();
    const { bindings, missing } = buildCredentialBindings(workflowDef.nodes, availableCreds);

    if (missing.length > 0) {
      return res.status(400).json({
        error: {
          code: 'INVALID_WORKFLOW_SPEC',
          message: `Cannot deploy: ${missing.length} credential(s) missing`,
          source: 'n8n-as-code-service'
        },
        missing,
      });
    }

    // Step 2: Inject credentials into workflow nodes
    const boundWorkflow = injectCredentialsIntoWorkflow(workflowDef, bindings);
    boundWorkflow.name  = meta.intent || `Aivory Workflow ${meta.draftId}`;
    boundWorkflow.settings = {
      ...(boundWorkflow.settings || {}),
      executionOrder: 'v1',
    };

    // Step 3: Deploy to n8n production
    const n8nHost = process.env.N8N_HOST    || 'http://localhost:5678';
    const apiKey  = process.env.N8N_API_KEY || '';

    const createRes = await fetch(`${n8nHost}/api/v1/workflows`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'X-N8N-API-KEY': apiKey },
      body:    JSON.stringify(boundWorkflow),
    });

    if (!createRes.ok) {
      throw new Error(`Deploy failed (${createRes.status}): ${await createRes.text()}`);
    }

    const deployed   = await createRes.json();
    const workflowId = String(deployed?.id ?? '');
    if (!workflowId) throw new Error('Deploy succeeded but no workflow ID returned');

    // Step 4: Activate if requested
    let activated = false;
    if (activate) {
      const activateRes = await fetch(`${n8nHost}/api/v1/workflows/${workflowId}/activate`, {
        method:  'POST',
        headers: { 'X-N8N-API-KEY': apiKey },
      });
      activated = activateRes.ok;
    }

    // Step 5: Persist deploy info to meta
    meta.status           = 'deployed';
    meta.deployedWorkflow = {
      workflowId,
      activated,
      deployedAt: new Date().toISOString(),
      workflowUrl: `${n8nHost}/workflow/${workflowId}`,
    };
    meta.updatedAt = new Date().toISOString();
    writeMeta(draft_id, meta);

    logInfo({ 
      event: 'success', 
      path: '/drafts/deploy', 
      status: 'ok', 
      draftId, 
      workflowId,
      activated 
    });

    return res.json({
      draft_id,
      workflowId,
      activated,
      workflowUrl: `${n8nHost}/workflow/${workflowId}`,
      boundCredentials: bindings.length,
      summary: activated
        ? `Workflow deployed and activated. Open: ${n8nHost}/workflow/${workflowId}`
        : `Workflow deployed (not activated). Open: ${n8nHost}/workflow/${workflowId}`,
    });
  } catch (error) {
    logError({
      event: 'error',
      path: '/drafts/deploy',
      error_message: error.message
    });
    res.status(error.status || 500).json({ error: true, message: error.message });
  }
});

app.post('/drafts/report', (req, res) => {
  try {
    const { draft_id } = req.body || {};
    if (!draft_id) return res.status(400).json({ error: true, message: 'draft_id is required' });
    res.json(buildSetupReport(readMeta(draft_id)));
  } catch (error) {
    res.status(error.status || 500).json({ error: true, message: error.message });
  }
});

app.post('/drafts/cleanup', (req, res) => {
  try {
    const { draft_id } = req.body || {};
    if (!draft_id) return res.status(400).json({ error: true, message: 'draft_id is required' });
    const { metaPath } = draftPaths(draft_id);
    const meta = readMeta(draft_id);
    meta.status = 'cleaned';
    meta.updatedAt = new Date().toISOString();
    fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2));
    res.json({ status: 'cleaned', draft_id });
  } catch (error) {
    res.status(error.status || 500).json({ error: true, message: error.message });
  }
});

const PORT = process.env.PORT || 3500;
app.listen(PORT, '127.0.0.1', () => {
  console.log(`n8n-as-code adapter running on 127.0.0.1:${PORT}`);
});
