/**
 * App Catalog
 *
 * Registry of all AVRY integration apps.
 * Ported from nextjs-console/lib/integrations/store.ts APP_CATALOG.
 */

const APP_CATALOG = [
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and notifications to Slack channels.',
    icon: '',
    authType: 'oauth',
    categories: ['Communication'],
    defaultAction: 'Send Message',
    oauthProvider: 'slack',
    connectLabel: 'Connect Slack',
    oauthScopes: ['chat:write', 'channels:read', 'users:read'],
    fields: [],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Use GPT models for text generation and analysis.',
    icon: '',
    authType: 'apiKey',
    categories: ['AI'],
    defaultAction: 'Generate Text',
    fields: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'sk-...', required: true }],
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Send transactional and marketing emails.',
    icon: '',
    authType: 'apiKey',
    categories: ['Communication'],
    defaultAction: 'Send Email',
    fields: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'SG.xxx', required: true }],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read and write Notion databases and pages.',
    icon: '',
    authType: 'oauth',
    categories: ['Databases'],
    defaultAction: 'Create Page',
    oauthProvider: 'notion',
    connectLabel: 'Connect Notion',
    oauthScopes: ['read_content', 'update_content', 'insert_content'],
    fields: [],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Sync contacts, deals, and CRM data.',
    icon: '',
    authType: 'oauth',
    categories: ['CRM'],
    defaultAction: 'Create Contact',
    oauthProvider: 'hubspot',
    connectLabel: 'Connect HubSpot',
    oauthScopes: ['crm.objects.contacts.read', 'crm.objects.contacts.write', 'crm.objects.deals.read'],
    fields: [],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Read and write Airtable bases and tables.',
    icon: '',
    authType: 'oauth',
    categories: ['Databases'],
    defaultAction: 'Create Record',
    oauthProvider: 'airtable',
    connectLabel: 'Connect Airtable',
    oauthScopes: ['data.records:read', 'data.records:write', 'schema.bases:read'],
    fields: [],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Automate GitHub issues, PRs, and repos.',
    icon: '',
    authType: 'oauth',
    categories: ['DevTools'],
    defaultAction: 'Create Issue',
    oauthProvider: 'github',
    connectLabel: 'Connect GitHub',
    oauthScopes: ['repo', 'read:user', 'user:email'],
    fields: [],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Create and update Jira issues and projects.',
    icon: '',
    authType: 'basic',
    categories: ['DevTools'],
    defaultAction: 'Create Issue',
    fields: [
      { key: 'username', label: 'Email', type: 'text', placeholder: 'you@company.com', required: true },
      { key: 'password', label: 'API Token', type: 'password', placeholder: 'ATATT...', required: true },
      { key: 'url', label: 'Jira Base URL', type: 'url', placeholder: 'https://yourorg.atlassian.net', required: true },
    ],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Sync leads, contacts, and opportunities.',
    icon: '',
    authType: 'oauth',
    categories: ['CRM'],
    defaultAction: 'Create Lead',
    oauthProvider: 'salesforce',
    connectLabel: 'Connect Salesforce',
    oauthScopes: ['api', 'refresh_token', 'id'],
    fields: [],
  },
  {
    id: 'http',
    name: 'HTTP / Custom API',
    description: 'Connect to any REST API with an API key.',
    icon: '',
    authType: 'apiKey',
    categories: ['Custom API'],
    defaultAction: 'HTTP Request',
    fields: [
      { key: 'apiKey', label: 'API Key or Bearer Token', type: 'password', placeholder: 'Bearer eyJ...', required: true },
      { key: 'url', label: 'Base URL', type: 'url', placeholder: 'https://api.example.com', required: false },
    ],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Send and receive emails via Gmail.',
    icon: '',
    authType: 'oauth',
    categories: ['Communication'],
    defaultAction: 'Send Email',
    oauthProvider: 'google',
    connectLabel: 'Sign in with Google',
    oauthScopes: ['openid', 'email', 'https://mail.google.com/'],
    fields: [],
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Read and write files in Google Drive.',
    icon: '',
    authType: 'oauth',
    categories: ['Storage'],
    defaultAction: 'Upload File',
    oauthProvider: 'google',
    connectLabel: 'Sign in with Google',
    oauthScopes: ['openid', 'email', 'https://www.googleapis.com/auth/drive'],
    fields: [],
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Read and write data in Google Sheets.',
    icon: '',
    authType: 'oauth',
    categories: ['Databases'],
    defaultAction: 'Write Data',
    oauthProvider: 'google',
    connectLabel: 'Sign in with Google',
    oauthScopes: ['openid', 'email', 'https://www.googleapis.com/auth/spreadsheets'],
    fields: [],
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Create and manage calendar events.',
    icon: '',
    authType: 'oauth',
    categories: ['Productivity'],
    defaultAction: 'Create Event',
    oauthProvider: 'google',
    connectLabel: 'Sign in with Google',
    oauthScopes: ['openid', 'email', 'https://www.googleapis.com/auth/calendar'],
    fields: [],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Send messages and notifications via Telegram bot.',
    icon: '',
    authType: 'apiKey',
    categories: ['Communication'],
    defaultAction: 'Send Message',
    fields: [{ key: 'apiKey', label: 'Bot Token', type: 'password', placeholder: '123456:ABC-DEF...', required: true }],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    description: 'Send WhatsApp messages via Twilio or Meta API.',
    icon: '',
    authType: 'apiKey',
    categories: ['Communication'],
    defaultAction: 'Send Message',
    fields: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Bearer ...', required: true }],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and notifications to Discord channels.',
    icon: '',
    authType: 'oauth',
    categories: ['Communication'],
    defaultAction: 'Send Message',
    oauthProvider: 'discord',
    connectLabel: 'Connect Discord',
    oauthScopes: ['identify', 'email', 'guilds', 'bot'],
    fields: [],
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'Send messages to Microsoft Teams channels.',
    icon: '',
    authType: 'oauth',
    categories: ['Communication'],
    defaultAction: 'Send Message',
    oauthProvider: 'microsoft',
    connectLabel: 'Sign in with Microsoft',
    oauthScopes: ['openid', 'email', 'profile', 'Chat.ReadWrite', 'ChannelMessage.Send'],
    fields: [],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    description: 'Send and manage emails via Microsoft Outlook.',
    icon: '',
    authType: 'oauth',
    categories: ['Communication'],
    defaultAction: 'Send Email',
    oauthProvider: 'microsoft',
    connectLabel: 'Sign in with Microsoft',
    oauthScopes: ['openid', 'email', 'profile', 'Mail.ReadWrite', 'Mail.Send'],
    fields: [],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Process payments and manage subscriptions.',
    icon: '',
    authType: 'apiKey',
    categories: ['Finance'],
    defaultAction: 'Create Payment',
    fields: [{ key: 'apiKey', label: 'Secret API Key', type: 'password', placeholder: 'sk_live_...', required: true }],
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Manage email marketing campaigns and audiences.',
    icon: '',
    authType: 'oauth',
    categories: ['Marketing'],
    defaultAction: 'Add Subscriber',
    oauthProvider: 'mailchimp',
    connectLabel: 'Connect Mailchimp',
    oauthScopes: ['access_full'],
    fields: [],
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Create and manage Trello boards, lists, and cards.',
    icon: '',
    authType: 'oauth',
    categories: ['Productivity'],
    defaultAction: 'Create Card',
    oauthProvider: 'trello',
    connectLabel: 'Connect Trello',
    oauthScopes: ['read', 'write', 'account'],
    fields: [],
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Create and manage tasks and projects in Asana.',
    icon: '',
    authType: 'oauth',
    categories: ['Productivity'],
    defaultAction: 'Create Task',
    oauthProvider: 'asana',
    connectLabel: 'Connect Asana',
    oauthScopes: ['default'],
    fields: [],
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Create and track issues in Linear.',
    icon: '',
    authType: 'oauth',
    categories: ['DevTools'],
    defaultAction: 'Create Issue',
    oauthProvider: 'linear',
    connectLabel: 'Connect Linear',
    oauthScopes: ['read', 'write', 'issues:create'],
    fields: [],
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Store and sync files with Dropbox.',
    icon: '',
    authType: 'oauth',
    categories: ['Storage'],
    defaultAction: 'Upload File',
    oauthProvider: 'dropbox',
    connectLabel: 'Connect Dropbox',
    oauthScopes: ['files.metadata.read', 'files.content.read', 'files.content.write'],
    fields: [],
  },
  {
    id: 'aws-s3',
    name: 'AWS S3',
    description: 'Upload and manage files in Amazon S3 buckets.',
    icon: '',
    authType: 'apiKey',
    categories: ['Storage'],
    defaultAction: 'Upload File',
    fields: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...', required: true },
      { key: 'secretAccessKey', label: 'Secret Access Key', type: 'password', placeholder: '...', required: true },
      { key: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
    ],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Send SMS and voice calls via Twilio.',
    icon: '',
    authType: 'apiKey',
    categories: ['Communication'],
    defaultAction: 'Send SMS',
    fields: [
      { key: 'accountSid', label: 'Account SID', type: 'text', placeholder: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'authToken', label: 'Auth Token', type: 'password', placeholder: '...', required: true },
    ],
  },
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Manage customer conversations and support tickets.',
    icon: '',
    authType: 'oauth',
    categories: ['CRM'],
    defaultAction: 'Create Conversation',
    oauthProvider: 'intercom',
    connectLabel: 'Connect Intercom',
    oauthScopes: ['read_users', 'write_users', 'read_conversations', 'write_conversations'],
    fields: [],
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Create and manage customer support tickets.',
    icon: '',
    authType: 'oauth',
    categories: ['CRM'],
    defaultAction: 'Create Ticket',
    oauthProvider: 'zendesk',
    connectLabel: 'Connect Zendesk',
    oauthScopes: ['read', 'write', 'tickets:read', 'tickets:write'],
    fields: [],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Manage orders, products, and customers in Shopify.',
    icon: '',
    authType: 'oauth',
    categories: ['E-Commerce'],
    defaultAction: 'Create Order',
    oauthProvider: 'shopify',
    connectLabel: 'Connect Shopify',
    oauthScopes: ['read_products', 'write_products', 'read_orders', 'write_orders'],
    fields: [],
  },
]

module.exports = { APP_CATALOG }
